// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: luminex/v1/luminex.proto

package v1

import (
	request "github.com/bikash-789/comm-protos/luminex/v1/request"
	response "github.com/bikash-789/comm-protos/luminex/v1/response"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_luminex_v1_luminex_proto protoreflect.FileDescriptor

const file_luminex_v1_luminex_proto_rawDesc = "" +
	"\n" +
	"\x18luminex/v1/luminex.proto\x12\n" +
	"luminex.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a luminex/v1/request/request.proto\x1a\"luminex/v1/response/response.proto2\xfa\x06\n" +
	"\aluminex\x12\\\n" +
	"\tGetHealth\x12\x16.google.protobuf.Empty\x1a#.luminex.v1.response.HealthResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12x\n" +
	"\fGetPRMetrics\x12%.luminex.v1.request.RepositoryRequest\x1a&.luminex.v1.response.PRMetricsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/gh/pr-metrics\x12\x81\x01\n" +
	"\x0fGetMonthlyStats\x12%.luminex.v1.request.RepositoryRequest\x1a).luminex.v1.response.MonthlyStatsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/gh/monthly-stats\x12x\n" +
	"\fGetRepoStats\x12%.luminex.v1.request.RepositoryRequest\x1a&.luminex.v1.response.RepoStatsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/gh/repo-stats\x12\x8d\x01\n" +
	"\x13GetContributorStats\x12%.luminex.v1.request.RepositoryRequest\x1a-.luminex.v1.response.ContributorStatsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/gh/contributor-stats\x12{\n" +
	"\rGetIssueStats\x12%.luminex.v1.request.RepositoryRequest\x1a'.luminex.v1.response.IssueStatsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/gh/issue-stats\x12\x8b\x01\n" +
	"\x12GetDetailedPRStats\x12%.luminex.v1.request.RepositoryRequest\x1a,.luminex.v1.response.DetailedPRStatsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/gh/detailed-pr-statsB1Z/github.com/bikash-789/comm-protos/luminex/v1;v1b\x06proto3"

var file_luminex_v1_luminex_proto_goTypes = []any{
	(*emptypb.Empty)(nil),                     // 0: google.protobuf.Empty
	(*request.RepositoryRequest)(nil),         // 1: luminex.v1.request.RepositoryRequest
	(*response.HealthResponse)(nil),           // 2: luminex.v1.response.HealthResponse
	(*response.PRMetricsResponse)(nil),        // 3: luminex.v1.response.PRMetricsResponse
	(*response.MonthlyStatsResponse)(nil),     // 4: luminex.v1.response.MonthlyStatsResponse
	(*response.RepoStatsResponse)(nil),        // 5: luminex.v1.response.RepoStatsResponse
	(*response.ContributorStatsResponse)(nil), // 6: luminex.v1.response.ContributorStatsResponse
	(*response.IssueStatsResponse)(nil),       // 7: luminex.v1.response.IssueStatsResponse
	(*response.DetailedPRStatsResponse)(nil),  // 8: luminex.v1.response.DetailedPRStatsResponse
}
var file_luminex_v1_luminex_proto_depIdxs = []int32{
	0, // 0: luminex.v1.luminex.GetHealth:input_type -> google.protobuf.Empty
	1, // 1: luminex.v1.luminex.GetPRMetrics:input_type -> luminex.v1.request.RepositoryRequest
	1, // 2: luminex.v1.luminex.GetMonthlyStats:input_type -> luminex.v1.request.RepositoryRequest
	1, // 3: luminex.v1.luminex.GetRepoStats:input_type -> luminex.v1.request.RepositoryRequest
	1, // 4: luminex.v1.luminex.GetContributorStats:input_type -> luminex.v1.request.RepositoryRequest
	1, // 5: luminex.v1.luminex.GetIssueStats:input_type -> luminex.v1.request.RepositoryRequest
	1, // 6: luminex.v1.luminex.GetDetailedPRStats:input_type -> luminex.v1.request.RepositoryRequest
	2, // 7: luminex.v1.luminex.GetHealth:output_type -> luminex.v1.response.HealthResponse
	3, // 8: luminex.v1.luminex.GetPRMetrics:output_type -> luminex.v1.response.PRMetricsResponse
	4, // 9: luminex.v1.luminex.GetMonthlyStats:output_type -> luminex.v1.response.MonthlyStatsResponse
	5, // 10: luminex.v1.luminex.GetRepoStats:output_type -> luminex.v1.response.RepoStatsResponse
	6, // 11: luminex.v1.luminex.GetContributorStats:output_type -> luminex.v1.response.ContributorStatsResponse
	7, // 12: luminex.v1.luminex.GetIssueStats:output_type -> luminex.v1.response.IssueStatsResponse
	8, // 13: luminex.v1.luminex.GetDetailedPRStats:output_type -> luminex.v1.response.DetailedPRStatsResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_luminex_v1_luminex_proto_init() }
func file_luminex_v1_luminex_proto_init() {
	if File_luminex_v1_luminex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_luminex_v1_luminex_proto_rawDesc), len(file_luminex_v1_luminex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_luminex_v1_luminex_proto_goTypes,
		DependencyIndexes: file_luminex_v1_luminex_proto_depIdxs,
	}.Build()
	File_luminex_v1_luminex_proto = out.File
	file_luminex_v1_luminex_proto_goTypes = nil
	file_luminex_v1_luminex_proto_depIdxs = nil
}
