// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: luminex/v1/request/request.proto

package request

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryRequest) Reset() {
	*x = RepositoryRequest{}
	mi := &file_luminex_v1_request_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryRequest) ProtoMessage() {}

func (x *RepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_luminex_v1_request_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryRequest.ProtoReflect.Descriptor instead.
func (*RepositoryRequest) Descriptor() ([]byte, []int) {
	return file_luminex_v1_request_request_proto_rawDescGZIP(), []int{0}
}

func (x *RepositoryRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RepositoryRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

var File_luminex_v1_request_request_proto protoreflect.FileDescriptor

const file_luminex_v1_request_request_proto_rawDesc = "" +
	"\n" +
	" luminex/v1/request/request.proto\x12\x12luminex.v1.request\"=\n" +
	"\x11RepositoryRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repoB>Z<github.com/bikash-789/comm-protos/luminex/v1/request;requestb\x06proto3"

var (
	file_luminex_v1_request_request_proto_rawDescOnce sync.Once
	file_luminex_v1_request_request_proto_rawDescData []byte
)

func file_luminex_v1_request_request_proto_rawDescGZIP() []byte {
	file_luminex_v1_request_request_proto_rawDescOnce.Do(func() {
		file_luminex_v1_request_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_luminex_v1_request_request_proto_rawDesc), len(file_luminex_v1_request_request_proto_rawDesc)))
	})
	return file_luminex_v1_request_request_proto_rawDescData
}

var file_luminex_v1_request_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_luminex_v1_request_request_proto_goTypes = []any{
	(*RepositoryRequest)(nil), // 0: luminex.v1.request.RepositoryRequest
}
var file_luminex_v1_request_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_luminex_v1_request_request_proto_init() }
func file_luminex_v1_request_request_proto_init() {
	if File_luminex_v1_request_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_luminex_v1_request_request_proto_rawDesc), len(file_luminex_v1_request_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_luminex_v1_request_request_proto_goTypes,
		DependencyIndexes: file_luminex_v1_request_request_proto_depIdxs,
		MessageInfos:      file_luminex_v1_request_request_proto_msgTypes,
	}.Build()
	File_luminex_v1_request_request_proto = out.File
	file_luminex_v1_request_request_proto_goTypes = nil
	file_luminex_v1_request_request_proto_depIdxs = nil
}
